### ISSUE TITLE
Need a type to represent "first-click attribution within a window"

### ISSUE THREAD

**Issue by dgrtwo** [datacamp/funneljoin#33]
One way to describe a funnel is "first-click attribution, but within an X-day window." I think it can be intuitively a bit confusing but still something people will request. Here's an example:

* A. User clicks an ad on day 1
* B. User clicks an ad on day 30
* C. User clicks an ad on day 40
* D. User converts on day 45

If someone wanted to do "first-click attribution within a 28-day window", the events that this should join would be B-D. However, I don't believe any existing options support this:

* first-first (or first-firstafter) without a window would be A-D
* first-first (or first-firstafter) with a 28 day window would have no matches
* lastbefore-firstafter would be C-D

I think this kind of join would be called something like `firstwithin-firstafter`, since unlike first- it would rely on the window.

**Comment by robinsones** [comment]
What about instead of a new type, have a new argument (e.g. `within`) that defaults to `FALSE`, but if `TRUE`, the getting all the valid pairs step and `filter_within_gap()` step happens before the filtering of `x_i` and `y_i` if type is `first` or `last`. 

For example, this would be a `first-firstafter` and `within = TRUE`. `after_join()` would get all the valid pairs, then filter within the 28 day gap, then apply the `first-firstafter` filter.

**Comment by robinsones** [comment]
added firstwithin as a type
